language: python
python:
  - 3.5
# command to install dependencies
install: 
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install pep8
# command to run tests
before_script:
 - pep8 --count --show-source --max-line-length=119 --exclude=migrations django/apimetaclub/apimetaclub/

script: 
    - python django/apimetaclub/manage.py test
    - coverage run django/apimetaclub/manage.py test
    
 
after_success: coveralls